# Cloudflare Worker configuration
account_id = "93bfcf72dfea0e9f2bf5563bc71052cf"
zone_id = "c192cf8ac042c681023493c52edd44c8"

# shared
type = "webpack"
webpack_config = "worker_webpack.config.js"

# default dev environment
name = "worker-dev"
workers_dev = true

# environment configuration
[env.staging]
name = "worker-staging"
route = "staging.deno.land/*"
workers_dev = false

# environment configuration
[env.production]
name = "worker"
route = "deno.land/*"
workers_dev = false
