name: ci

on: [push, pull_request]

jobs:
  website:
    runs-on: ubuntu-latest
    env:
      working-directory: web
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn --frozen-lockfile
        working-directory: ${{env.working-directory}}
      - run: yarn run lint
        working-directory: ${{env.working-directory}}
      - run: yarn format --check
        working-directory: ${{env.working-directory}}
      - run: CI=true yarn test
        working-directory: ${{env.working-directory}}
  worker:
    runs-on: ubuntu-latest
    env:
      working-directory: worker
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn --frozen-lockfile
        working-directory: ${{env.working-directory}}
      - run: yarn format --check
        working-directory: ${{env.working-directory}}
      - run: CI=true yarn test
        working-directory: ${{env.working-directory}}
      - name: Publish Production
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && github.repository == 'denoland/deno_website2'
        uses: cloudflare/wrangler-action@1.0.0
        with:
          environment: 'production'
          apiKey: ${{ secrets.cloudflareKey }}
          email: ${{ secrets.email }}
      - name: Publish Staging
        if: github.event_name == 'push' && github.repository == 'denoland/deno_website2'
        uses: cloudflare/wrangler-action@1.0.0
        with:
          environment: 'staging'
          apiKey: ${{ secrets.cloudflareKey }}
          email: ${{ secrets.email }}
